### ISSUE TITLE
refactor: allow to copy dot files without running all setup.sh script

### ISSUE THREAD

**Issue by dportabella** [johnwyles/bootstrap-macos#1]
refactor:
- move out backupDotfiles and copyDotfiles from setup.sh to ./scripts/dot_files.sh, and
- move out addTerminalToPrivacyAccessibility from setup.sh to ./scripts/addTerminalToPrivacyAccessibility.sh (or similar name).

so that we can run ./scripts/dot_files.sh individually without running the whole setup.sh.

**Comment by johnwyles** [comment]
The thing here is that the dotfiles `.zshrc` and `.bash_profile` from the (backup and) copy process are highly coupled with the rest of the underlying scripts to the point where you almost certainly want to start with a fresh copy of your dotfiles.  If you already have *some* dotfiles configuration you would like to keep for your user on the machine then I highly recommend, for this project, to perform this as a new user and copy over manually the dotfile wizardry you had in place from your old user to the new one you create.

As you run through this let me know what you think or suggest in this regard and it wouldn't take long to update/make this change.

**Comment by dportabella** [comment]
how is .bash_profile highly coupled with the rest of the underlying scripts?
I like the option to execute the scripts individually (dotfiles.sh, xcode_cli_tools.sh, brew_install.sh, java.sh, productivity.sh...).

**Comment by johnwyles** [comment]
This is *mostly* OK but with Bash the script here https://github.com/johnwyles/bootstrap-macos/blob/master/scripts/shells/bash.sh#L13 will make some changes that inevitably are tied to `.bash_profile`. With all of the tie-ins to the installs for things like `rvm`, `nvm`, and `pyenv` the file is constantly changed yet again. The `.bash_profile` you end up with in the end after installing `ruby`, `python`, and `javascript` scripts is the one I have in `dotfiles`https://github.com/johnwyles/bootstrap-macos/blob/master/dotfiles/.bash_profile . So if you installed just some of these scripts you would end up with a state of your `.bash_profile` I have not verified or know which will work (maybe it will?). Also this `.bash_profile` file contains all of the plugins needed for these things and appearance customizations. That one is pretty straight forward, however with Zsh it gets a lot more messy if I recall...

With Zsh the script here https://github.com/johnwyles/bootstrap-macos/blob/master/scripts/shells/zsh.sh#L16 will make some changes which will inevitably be tied back to `.zshrc`. There are a lot of customizations I make to `.zshrc` not only for `rbenv`, `nvm`, and `pyenv` like with Bash above but also for customizations to the shells appearance and plugins which are installed that tie into the fonts, etc. etc.

It all boils down to this: if you selectively run some of these scripts and not others the `.zshrc` or `.bash_profile` I supply in `dotfiles` will either be overkill and/or the default one your shell environment has may not have customizations for some of the installs other scripts run for things that are installs. This primarily centers around Ruby, Node, and Python.

**Comment by johnwyles** [comment]
I think this is mostly resolved in the approach that this user does have some choice but largely this approach is very prescriptive so users will have to take this approach and make their tweaks or tailor this
